# -*- coding: utf-8 -*-
"""Primer_Previo_CdD.ipynb Solución al examen 1 de Ciencia de Datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4_nthlky3CRp9OIJl9pOExPBtUHWIRD

# **Solución Primer Previo de Ciencia de Datos**

**Estudiantes del grupo:**

1. Roberto Antonio Jaimes Manzano - 1162165   
2. Jhonatan Fernando Gómez Ballesteros - 1162066

**Docente: M.Sc. geiner Giovanny Barbosa Casanova**

## 1. Selección del Dataset

Seleccionaremos un dataset del repositorio disponible en linea Kaggle, el cual se llama UCI ML Air Quality Dataset, este cuenta con todos los requirimientos planteados en el primer punto:

1. Volumen mínimo de columnas y filas, al menos 500 registros (filas) y 6 variables (coumnas).
2. Tipología de variables, incorpora una combinación de atributos numéricos (continuos/discretos) y categóricos (nominales/ordinales).
3. Incluir al menos una columna de fecha, hora o marca de tiempo(*timestamp*) adecuada para el análisis de series temporales.
4. Contiene (o induce pedagógicamente) valores faltantes, valores atípicos (*outliers*) y características que requieran codificación y/o escalado.
"""

# Seleccion de DataFrame y primeros pasos

import pandas as pd
from IPython.display import display

# Google Colab is unavailable when running the script locally.
data_path = 'C:\\Users\\Rober\\OneDrive\\Documents\\piton\\Data_Scienc\\AirQualityUCI.csv'

df = pd.read_csv(data_path, sep=',', decimal='.') #acomoda el modo de leer el archivo porque el csv original usa ";" como separador y "," como decimal

df = df.loc[:, ~df.columns.str.contains('^Unnamed')] #elimina columnas vacías que trar el archivo original

df = df.dropna(how='all') #elimina las filas totalmente vacías al final del archivo (si es que las hay)

print("Primeras filas: ")
display(df.head())

print("\nÚltimas filas: ")
display(df.tail())

print(f"\nDimensiones: {df.shape[0]} filas x {df.shape[1]} columnas")

print("\nTipos de datos por columnas: ")
print(df.dtypes)

print("\nResumen estadístico:")
display(df.describe(include='all'))

"""## 2. Metodos y manejo de datos

En este segundo punto se cuantificará y se visualizaran los valores faltantes de cada variable, informando tanto los recuentos absolutos como los porcentajes.

Ademas se implementará y comparará explícitamente métodos para el manejo de datos faltantes, incluyendo técicas de eliminación, imputación estadística e interpolación.

Finalmente se justificará el método mas viable y apropiado basándose en el contexto del dominio y las características subyacentes del conjunto de datos.


"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns # opcional mapa de calor para detectar daños en bloque (propuesto por la ia)
# primero toca convertír los -200 a Nan ya que en este caso representan lo mismo pero para poder trabajarlo es necesario transformarlo

cols_num = df.select_dtypes(include=[np.number]).columns # operamos en solo las columnas con valores numericos

df[cols_num] = df[cols_num].replace(-200, np.nan) #Reemplazamos -200 por NaN solo en las columnas numericas

falta_abs = df.isnull().sum() # Conteo mediante creacion de df tipo true/falase y suma con sum.
falta_pct = (df.isnull().mean() * 100).round(2) # Lo de antes pero en porcentaje

resum_falta = pd.DataFrame({
    'Faltantes (abs)': falta_abs,
    'Faltantes (%)': falta_pct
}).sort_values(by='Faltantes (%)', ascending=False)

print("Resumen de valores faltantes:")
display(resum_falta)

plt.figure(figsize=(10, 5))
resum_falta['Faltantes (%)'].plot(kind='bar', color='indianred')
plt.ylabel('Porcentaje de Faltantes')
plt.title('Porcentaje de Valores Faltantes por Variable')
plt.xticks(rotation=75)
plt.tight_layout()
plt.show()

# opcional -
plt.figure(figsize=(12, 5))
sns.heatmap(df[cols_num].isnull(), cbar=False, cmap='Reds')
plt.title('Mapa de Calor de Valores Faltantes')
plt.show()

# aplicación de metodos

## Metodo 1: eliminación (listwise deletion)
df_del = df.dropna(subset=cols_num)
print(f"Filas originales: {len(df)} | Filas luego de eliminar: {len(df_del)}")

## Metodo 2: imputación estadística (mediana, robusta a outliers)
df_imp = df.copy()
df_imp[cols_num] = df_imp[cols_num].fillna(
    df_imp[cols_num].median()
)

## Metodo 3: interpolación (lineal, aprovechando el orden temporal)
df_interp = df.copy()
df_interp[cols_num] = df_interp[cols_num].interpolate(method='linear')

# ahora lo implementamos en una de las variables para ver el efecta de cada una graficamente ej: CO(GT)
fig, axes = plt.subplots(3, 1, figsize=(12, 8), sharex=True)

df_imp['CO_GT'].plot(ax=axes[0], title='Imputación con mediana', color='steelblue')
df_interp['CO_GT'].plot(ax=axes[1], title='Interpolación lineal', color='seagreen')
df['CO_GT'].plot(ax=axes[2], title='Original (con huecos)', color='gray')

plt.tight_layout()
plt.show()

"""### Justificación luego de comparación y graficas

Una vez analizados los graficos es mas sencillo poder deducir cual es el metodo mas conveniente en este caso y variable particular:



*   Interpolación lineal: es la más adecuada aquí porque los datos son una serie temporal continua (mediciones horarias de sensores) también los huecos suelen ser cortos (fallas puntuales del sensor) y el valor real probablemente esté entre el punto anterior y el siguiente, no en el valor "típico" global.

*   Imputación estadística (mediana): Es razonable para variables con pocos faltantes dispersos, pero "aplana" la señal y no respeta que la concentración de un gas varía a lo largo del día (patrones de tráfico, temperatura), así que introduce sesgo en un análisis de series de tiempo como vemos en la gráfica.

*   Eliminación: En este caso se descartó como método principal ya que se perdería una fracción grande de filas porque NMHC(GT) suele tener más del 90% de faltantes en este dataset (podemos ver el total absoluto de faltantes en el resumen del inicio). Sirve solo como comparación, no como solución final.

## 3. Identificación y abordaje de los valores atípicos

Ahora se identifican los valores atípicos (outliers) y se les da el tratamiento adecuado dependiendo de la finalidad.
"""

import matplotlib.pyplot as plt

# Boxplots vista general de todas las variables numéricas
n_cols = len(cols_num)
fig, axes = plt.subplots(nrows=(n_cols + 3) // 4, ncols=4, figsize=(18, 4 * ((n_cols + 3) // 4)))
axes = axes.flatten()

for i, col in enumerate(cols_num):
    axes[i].boxplot(df_interp[col].dropna())
    axes[i].set_title(col, fontsize = 10)

# Ocultamos los ejes sobrantes si el grid no cierra exacto
for j in range(i + 1, len(axes)):
    axes[j].axis('off')

plt.tight_layout()
plt.show

# Calculo de límites IQR por columna
resum_outliers = {}

for col in cols_num:
  Q1 = df_interp[col].quantile(0.25)
  Q3 = df_interp[col].quantile(0.75)
  IQR = Q3 - Q1
  limite_inf = Q1 - 1.5 * IQR
  limite_sup = Q3 + 1.5 * IQR

  n_outliers = ((df_interp[col] < limite_inf) | (df_interp[col] > limite_sup)).sum()
  pct_outliers = round(n_outliers / len(df_interp) * 100, 2)

  resum_outliers[col] = {
      'Límite inf': round(limite_inf, 2),
      'Límite sup': round(limite_sup, 2),
      'N° outliers': n_outliers,
      'Porcentaje outliers': pct_outliers
  }

  df_resum_outliers = pd.DataFrame(resum_outliers).T.sort_values(by='Porcentaje outliers', ascending=False)
  display(df_resum_outliers)

# Visualización de los outliers marcados sobre la serie de tiempo
col = 'CO_GT' # Esta columna se puede cambiar dependiendo de que variable se quiera analizar

Q1 = df_interp[col].quantile(0.25)
Q3 = df_interp[col].quantile(0.75)
IQR = Q3 - Q1
limite_inf = Q1 - 1.5 * IQR
limite_sup = Q3 + 1.5 * IQR

es_outlier = (df_interp[col] < limite_inf) | (df_interp[col] > limite_sup)

plt.figure(figsize=(14, 5))
plt.plot(df_interp[col].values, color='steelblue', label='serie original', linewidth=0.8)
plt.scatter(df_interp[es_outlier].index, df_interp[col][es_outlier], color='red', label='Outliers (IQR)', zorder=5)
plt.axhline(limite_inf, color='green', linestyle='--', label='Límite inferior')
plt.axhline(limite_sup, color='green', linestyle='--', label='Límite superior')
plt.legend()
plt.title(f'Outliers detectados en {col}')
plt.legend()
plt.tight_layout()
plt.show()

# Tratamiento de datos (capping)
df_sin_outliers = df_interp.copy()

for col in cols_num:
  Q1 = df_interp[col].quantile(0.25)
  Q3 = df_interp[col].quantile(0.75)
  IQR = Q3 - Q1
  limite_inf = Q1 - 1.5 * IQR
  limite_sup = Q3 + 1.5 * IQR

  df_sin_outliers[col] = df_sin_outliers[col].clip(lower=limite_inf, upper=limite_sup)

"""## 4. Preprocesamiento y Escalado

**1. Codificación de variables categóricas:**
*   **Codificación Ordinal:** Usamos `OrdinalEncoder` en la variable `Nivel_Contaminacion` porque sus categorías tienen un orden lógico (Bajo < Moderado < Alto).
*   **One-Hot Encoding:** Aplicamos `get_dummies` a `Periodo_Dia` ya que es una variable nominal (Mañana, Tarde, Noche) y no queremos que el modelo asuma falsas jerarquías matemáticas entre los horarios.

**2. Justificación del método de escalado:**
Al comparar la Normalización (`MinMaxScaler`) y la Estandarización (`StandardScaler`), la mejor opción para este dataset es **StandardScaler**. Los datos de los sensores de calidad del aire suelen tener muchos picos bruscos (outliers) debido al tráfico o cambios de clima. `MinMaxScaler` es muy sensible a estos picos y comprimiría todos los datos normales en un rango demasiado pequeño. La estandarización, en cambio, es mucho más robusta frente a estos valores atípicos.
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder, MinMaxScaler, StandardScaler

# Inducción/Creación de variables categóricas pedagógicas

# Variable Ordinal: Nivel de CO categorizado en 'Bajo', 'Moderado', 'Alto'
condiciones_co = [
    (df['CO_GT'] <= 1.5),
    (df['CO_GT'] > 1.5) & (df['CO_GT'] <= 3.0),
    (df['CO_GT'] > 3.0)
]
categorias_co = ['Bajo', 'Moderado', 'Alto']
df['Nivel_Contaminacion'] = np.select(condiciones_co, categorias_co, default='Moderado')

# Variable Nominal: Periodo del día según la hora
horas = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.hour
condiciones_hora = [
    (horas >= 6) & (horas < 12),
    (horas >= 12) & (horas < 18),
    (horas >= 18) | (horas < 6)
]
periodos = ['Mañana', 'Tarde', 'Noche']
df['Periodo_Dia'] = np.select(condiciones_hora, periodos, default='Noche')

print(" Dataframe con Variables Categóricas Creadas")
print(df[['CO_GT', 'Nivel_Contaminacion', 'Periodo_Dia']].head())

# APLICACIÓN DE CODIFICACIÓN (CATEGORICAL ENCODING)

# A. Codificación Ordinal para 'Nivel_Contaminacion'
orden_prioridad = [["Bajo", "Moderado", "Alto"]]
encoder_ordinal = OrdinalEncoder(categories=orden_prioridad)
df['Nivel_Contaminacion_Cod'] = encoder_ordinal.fit_transform(df[['Nivel_Contaminacion']])

# B. Codificación One-Hot para 'Periodo_Dia'
df_encoded = pd.get_dummies(df, columns=['Periodo_Dia'], dtype=int)

print("\n Resultado tras Codificación Ordinal y One-Hot")
print(df_encoded[['Nivel_Contaminacion', 'Nivel_Contaminacion_Cod', 'Periodo_Dia_Mañana', 'Periodo_Dia_Tarde', 'Periodo_Dia_Noche']].head())

# APLICACIÓN Y CONTRASTE DE ESCALADO DE CARACTERÍSTICAS
variables_continuas = ['PT08_S1_CO', 'C6H6_GT', 'T', 'RH']

# Imputación rápida por media para permitir escalado en columnas continuas
df_continuas = df_encoded[variables_continuas].fillna(df_encoded[variables_continuas].mean())

# A. Normalización (MinMaxScaler -> Rango [0, 1])
scaler_minmax = MinMaxScaler()
df_norm = pd.DataFrame(scaler_minmax.fit_transform(df_continuas), columns=[f"{col}_Norm" for col in variables_continuas])

# B. Estandarización (StandardScaler -> Media 0, Desv 1)
scaler_std = StandardScaler()
df_std = pd.DataFrame(scaler_std.fit_transform(df_continuas), columns=[f"{col}_Std" for col in variables_continuas])

# Unificación para comparación de estadísticas
df_comparacion = pd.concat([df_norm.head(3), df_std.head(3)], axis=1)

print("\n Comparación de Muestras: Normalización vs Estandarización")
display(df_comparacion)

"""## 5. Manipulación de Datos y Series de Tiempo

1. Manipulación avanzada:
Primero, filtramos los escenarios más críticos (alta temperatura combinada con alto benceno). Luego, usamos `groupby` para extraer los promedios de cada nivel de contaminación, y construimos una tabla pivote (`pivot_table`) para analizar cómo cambia el Monóxido de Carbono (CO) según el momento del día y la severidad de la contaminación.

2. Procesamiento de Series de Tiempo:
*   Índice temporal: Unimos las columnas de fecha y hora originales y las convertimos al formato unificado `Datetime`, dejándolo como el índice principal del DataFrame.
*   Remuestreo (Resampling): Agrupamos los datos a una frecuencia diaria (`'D'`) para ver el comportamiento macroscópico de los gases, eliminando el ruido de los cambios hora a hora.
*   Promedio Móvil (Rolling Mean): Aplicamos una media móvil con una ventana de 24 horas a la señal de CO. Esto nos ayuda a suavizar la curva (filtrando el ciclo normal de día/noche) para identificar cuál es la verdadera tendencia de contaminación con el paso de los días.
"""

# MANIPULACIÓN DE DATOS AVANZADA

# Filtrado Condicional Avanzado
umbral_c6h6 = df_encoded['C6H6_GT'].mean()
df_critico = df_encoded[(df_encoded['T'] > 25.0) & (df_encoded['C6H6_GT'] > umbral_c6h6)]
print(f"Registros críticos encontrados (T > 25°C y C6H6_GT > {umbral_c6h6:.2f}): {len(df_critico)}")

# Agregación por Grupos (groupby)
df_resumen_grupo = df_encoded.groupby('Nivel_Contaminacion')[['CO_GT', 'Nox_GT', 'T', 'RH']].mean().reset_index()
print("\n Promedios por Nivel de Contaminación (groupby)")
display(df_resumen_grupo)

# Reestructuración de Datos (pivot_table)
df_pivote = df.pivot_table(index='Nivel_Contaminacion', columns='Periodo_Dia', values='PT08_S1_CO', aggfunc='mean')
print("\n Tabla Pivote: Promedio de PT08_S1_CO")
display(df_pivote)

# PROCESAMIENTO DE SERIES DE TIEMPO

# Conversión de las columnas 'Date' y 'Time' a tipo Datetime unificado
df_encoded['Datetime'] = pd.to_datetime(
    df_encoded['Date'].astype(str) + ' ' + df_encoded['Time'].astype(str),
    errors='coerce'
)

# Designación del campo Datetime como Índice del DataFrame
df_time = df_encoded.dropna(subset=['Datetime']).set_index('Datetime').sort_index()
print("\n DataFrame con DatetimeIndex Configurado")
print(df_time[['CO_GT', 'PT08_S1_CO', 'T']].head())

# Remuestreo Temporal (Resampling a Frecuencia Diaria 'D')
df_diario = df_time[['CO_GT', 'PT08_S1_CO', 'C6H6_GT', 'T']].resample('D').mean()
print("\n Datos Remuestreados a Frecuencia Diaria (Primeros 5 días)")
display(df_diario.head())

# Promedio Móvil (Rolling Mean) con Ventana de 24 horas para Suavizar la Señal
df_time['PT08_S1_Suavizado'] = df_time['PT08_S1_CO'].rolling(window=24, min_periods=1).mean()

print("\n Comparación: Señal Original vs Señal Suavizada (Rolling Mean 24h)")
display(df_time[['PT08_S1_CO', 'PT08_S1_Suavizado']].head(10))